name: matrix_sdk_ffi
version: 0.0.1
publish_to: 'none'
description: Generated Dart FFI bindings for Matrix Rust SDK via UniFFI

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  meta: ^1.11.0
  collection: ^1.18.0
